services:
  - type: web
    name: ciblorgasport-auth-service
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      # Render fournit automatiquement DATABASE_URL, DB_USER, DB_PASSWORD
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION_MS
        value: 86400000

databases:
  - name: ciblorgasport-db
    databaseName: glop
    user: admin
    plan: free