services:
  - type: web
    name: ciblorgasport-auth-service
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: ciblorgasport-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION_MS
        value: 86400000

databases:
  - name: ciblorgasport-db
    databaseName: glop
    user: admin
    plan: free